# Generated by Django 5.1.4 on 2025-01-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_delete_user'),
    ]

    operations = [
    ]
