# Generated by Django 5.1.4 on 2025-01-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_observacoes_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(default='Título padrão', max_length=255),
        ),
    ]
