# Generated by Django 5.1.4 on 2025-01-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_previsao_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('publica', 'Pública'), ('interna', 'Interna')], default='publica', max_length=10),
        ),
    ]
